version: 0.2

phases:
  pre_build:
    commands:
      - echo Preparing for build...
  build:
    commands:
      - echo Building the Spring Boot application...
      - mvn clean install
  post_build:
    commands:
      - echo Building the Spring Boot application...
artifacts:
  files:
    - target/aws-demo-docker.jar
